name: Create swift packages
description: Create swift packages

inputs:
  version:
    description: "Version of the package"
    required: true

runs:
  using: "composite"
  steps:
    - uses: ./.github/workflows/actions/prepare
    - name: Create Swift Package
      shell: bash
      run: ./gradlew createSwiftPackage -Pversion=${{ inputs.version }}
    - name: Remove xcframework
      shell: bash
      run: rm -r */build/swiftpackage/*.xcframework
    - uses: actions/upload-artifact@v4
      with:
        name: oidc-swiftpackages
        path: oidc-*/build/swiftpackage/*
        retention-days: 1